#!/bin/bash

echo "starting grafana-server..."
cd /root/grafana/src/github.com/grafana/grafana
pwd
./bin/linux-amd64/grafana-server &

sleep 5
jobs
sleep 5

echo "starting snmp exporter"
cd /root/go/src/github.com/prometheus/snmp_exporter
pwd
./snmp_exporter &

sleep 5

echo "currently running jobs:"
jobs
sleep 5
