#!/bin/bash

# Navigate to /opt/splunk/etc/apps
# Go into each directory to see if the file "savedsearches.conf" exists

# If no, move on to next directory
# If yes:
#     - Generate snapshot
#         - copy the savedsearches.conf file to new directory with the following format:
#         - config_<current-date>/<app><local/default>savedsearches.conf
#     - Read config file using configparser and save to csv




# # Find all directories with savedsearches.conf (COMPLETED)
# echo "Searching for apps with default folder..."

# cd /opt/splunk/etc/apps

# IFS=' ' read -r -a  targets <<< `find . -name "savedsearches.conf"`
# echo "There are a total of ${#targets[@]} savedsearches.conf"
# echo "the directories are as follow:"=
# touch master.conf
# for (( i = 0 ; i < ${#targets[@]} ; i++));do
#     echo "${targets[i]}"

#     # create a master savedsearches.conf with all records (COMPLETED)
#     # cat "${targets[i]}" >> master.conf
# done

# Extract savedsearches.conf into .csv 

cd /root/conf-extraction
python3.6 app.py